<?php

// This file is generated by Composer
//require_once '../vendor/autoload.php';
require_once '../../vendor/autoload.php';


//Get all the repository information (Not sure if we need it)
//$repositories = $client->api('user')->repositories('TeamWorkFlo');
//print_r($repositories);


//$client = new \Github\Client();
//$commits = $client->api('repo')->commits()->all('TeamWorkFlo', 'teamworkflo', array('sha' => 'master'));


$client = new \Github\Client();
$branches = $client->api('repo')->branches('TeamWorkFlo', 'teamworkflo');
$branches_array = array();

foreach($branches as $branch){

array_push($branches_array, $branch['name']);
}

print_r($branches_array);

//echo json_encode($branches);


function getBranches(){
$client = new \Github\Client();
$branches = $client->api('repo')->branches('TeamWorkFlo', 'teamworkflo');
//print_r($branches);
return json_encode($branches);
}


function getCommitsFromBranch($branch_name){
//Get all commits from a particular branch in this case master.
$client = new \Github\Client();
$commits = $client->api('repo')->commits()->all('TeamWorkFlo', 'teamworkflo', array('sha' => $branch_name));
//print_r($commits);
return json_encode($commits);
}





?>
